---
# tasks file for packer

- name: install unzip
  yum:
    name: unzip
    state: present
  become: yes

- name: download packer zip
  get_url:
    url: "{{ packer_zip_url }}"
    dest: /tmp/packer.zip
    
- name: Add the user 'packer'
  user:
    name: packer
    comment: packer

- name: unpack packer
  unarchive:
    src: /tmp/packer.zip
    dest: /usr/bin
    copy: no
  become: yes

- name: remove packer zip
  file:
    path: /tmp/packer.zip
    state: absent
